[package]
name = "msi-extract"
version = "0.1.0"
edition = "2024"
description = "A library to extract files from MSI packages."
license = "MIT"

[dependencies]
cab = "0.6.0"
cfb = "0.10.0"
itertools = "0.14.0"
msi = "0.8.0"
thiserror = "2.0.12"