[package]
name = "sidecar-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
futures-util = "0.3.31"
memchr = "2.7.5"
object = "0.37.1"
reqwest = { version = "0.12.22", features = ["stream"] }
sevenz-rust = "0.6.1"
tokio = { version = "1.46.1", features = ["full"] }
